name = "snappost-serve"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "TENANT_KV"
id = "8d9afa8bc95b4600b8779a62309c15aa"
preview_id = "8d9afa8bc95b4600b8779a62309c15aa"

[vars]
CF_ACCOUNT_ID = "..."
CF_API_TOKEN = "..."

[[routes]]
pattern = "*.snappost.app/*"
zone_name = "snappost.app"

[[routes]]
pattern = "snappost.app/*"
zone_name = "snappost.app"
